### ISSUE TITLE
Tab query failure in extension

### ISSUE THREAD

**Issue by wickedDesigns** [shogerr/bluprntr#2]
I've attempted to follow the directions, but I get this error in the extension when I start up a video on the site:

> Error handling response: TypeError: Cannot read property 'id' of undefined
> 
> Context:
> devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@94f915a8d7c408b09cc7352161ad592299f384d2/&can_dock=true&dockSide=undocked
> 
> Stack Trace:
> plugin.js:8 (anonymous function)

It looks like for some reason, the tab running the video isn't showing up as both active and audible.  I'm not sure how best to debug further.

**Comment by kprantis** [comment]
I am also experiencing this issue.

**Comment by shogerr** [comment]
Thanks @kprantis and @wickedDesigns for the report. The tab query is very weak:
```
chrome.tabs.query({active:true, audible: true}, function(tab) {
```
and so the basic requirements are the tab is active, and it is playing audio. I was looking at that query today and it needs to be improved.

Here is what typical output should look like after clicking a class: 
```
saw: Machine Embroidery With Knits - 03 - Embroidering T-Shirts & Onesies
grabbing: Machine Embroidery With Knits - 03 - Embroidering T-Shirts & Onesies
Starting download: Machine Embroidery With Knits - 03 - Embroidering T-Shirts & Onesies
```
and then go on to report the download complete.

There are a couple of ways to troubleshoot chrome extensions, and they all are painful. With @wickedDesigns  report, it's for sure the plugin.js failing. Let me go back and make sure I'm not using some old code, but the way I troubleshoot this problem is to have the plugin.js send to the websocket server just hardcoded values. Then get those working, and build off of that. 

There is one way to get output from the extension, and it involves:
1. Open developer tools;
2. Detach the developer tools;
3. Press ctrl+shift+j and open up a _second_ developer tools panel for the developer tools panel.. 

It's very silly.

One process I go through to get the chrome extension working is to:
1. close developer tools;
2. refresh the page;
3. open developer tools.

**Comment by kprantis** [comment]
So you will have to bear with me. While I am comfortable with programming, I have not done much javascript/nodejs/web work. :)

Here is a screenshot of the page I am on:

![Screen Shot 2020-06-01 at 5 20 44 PM](https://user-images.githubusercontent.com/1007568/83463631-d3ab7680-a42b-11ea-8e95-9378f72269be.png)

Closing devtools, refreshing the page, and re-opening makes no difference. 

If I open a devtools of a devtools it doesn't seem to do much more than share the same error the chrome extentions page was telling me:

![Screen Shot 2020-06-01 at 5 22 28 PM](https://user-images.githubusercontent.com/1007568/83463691-0c4b5000-a42c-11ea-824c-52657659f5f2.png)

Definitely no output at all on my server after the "Downloading to" message.

I tried to do it where I was very behaved and left the tab in focus and can see with the speaker on the tab that it is registering the tab is playing audio, but no dice.

**Comment by shogerr** [comment]
Cool, thanks. Hmm, so I wonder if @wickedDesigns also is on a Mac. That could be the common thread here. I would try that tactic of replacing the code in `content.js` with some hardcoded values, and comment out all the other code. If the chrome extensions is generally working, values should come through to the server. Then we can chip away at which call is breaking this.

**Comment by kprantis** [comment]
Do you mean like this?

![Screen Shot 2020-06-01 at 5 31 23 PM](https://user-images.githubusercontent.com/1007568/83464229-6e588500-a42d-11ea-8de8-03ef09483d46.png)

I did the above change, reloaded the plugin, closed devtools, refreshed page, reopened devtools on network tab, and hit play, and it made no difference, and there is still no server output...

Is there a way to easily test if there could be some sort of firewall or some such issue making the server unaccessible?

**Comment by wickedDesigns** [comment]
I'm away from home and my desktop right now, so I can't test anything out, but I'm using Windows 10 there, so that's not the issue.  I'm wondering if there might be a delay between when the request goes out and when the video actually starts playing (and thus the audible property becoming true).

**Comment by kprantis** [comment]
I wonder if the 'id' error is a red herring. When I change the sendResponse I no longer get that error, or any errors regarding the plugin, but I still get no output in the node server output.

**Comment by adammenges** [comment]
FWIW we're seeing the issue on Ubuntu, too.

**Comment by shogerr** [comment]
> I wonder if the 'id' error is a red herring. When I change the sendResponse I no longer get that error, or any errors regarding the plugin, but I still get no output in the node server output.

What that error is saying is that nothing is coming through from the content.js script to send as a data, so it fails when it tries to read the data on the other end. I ran into this a lot while building the app, and this happens when anything in the content.js script fails to execute. 

@kprantis yep. Exactly like that. And your ws helps us tackle if its a firewall type issue. Thanks.

The extension code (content.js) probably needs some try catch blocks, and then that should be logged to a file, or passed to the server for error display. That's probably what I'll work on.

Once I got things working on my end, I didn't dig too deep on how Chrome wants a developer to debug scripts that don't output to console. I guess there it's going to have to happen though!

**Comment by shogerr** [comment]
With committ fa0bbb, verbose output can be enabled by right clicking the bluprntr icon, and selecting 'Debug mode'. I've also added a basic check to the tab to at least avoid the extension running into an uncaught error. Hopefully this gets things setup to be worked a little easier.

**Comment by shogerr** [comment]
I've pushed quite a big change today 9820bdf. Please pull the new code if you were having problems before. The debug mode will be added later. It may have caused some slowdown, maybe not. But, I did take time to clean up the output for the program, and add a little test server.

Start the test server with
```
yarn test-server
```

Here's a screenshot of the new server output.

![image](https://user-images.githubusercontent.com/10454476/83650788-97802f00-a56d-11ea-8a5f-338edaf2ec0c.png)

**Comment by shogerr** [comment]
I believe I've cleaned up some of the bigger problems with the way the extension was performing. In order to close this issue, the following changes have been made to the project as of commit 94decfc:

* removed the audible filter from the tab query;
* increased server logging clarity and verbosity;
* added debug mode to the chrome extension that logs to the developer tools console.

If you encounter problems related to tab queries, please don't hesitate to open a new issue.
